name: weather_app
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  flutter_screenutil: ^5.9.0
  dio: ^5.4.0
  geolocator: ^10.1.0
  flutter_easyloading: ^3.0.5
  panara_dialogs: ^0.1.4
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat_regular.ttf
        - asset: assets/fonts/montserrat_light.ttf
          weight: 300
        - asset: assets/fonts/montserrat_bold.ttf
          weight: 700
